[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bf_interpreter"
path = "src/bf_interpreter.rs"

[[bin]]
name = "bf_ir"
path = "src/bf_ir.rs"

[[bin]]
name = "bf_jit"
path = "src/bf_jit.rs"

[dependencies]
